Blogtask/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('userApp.urls')),
    path('blog/',include('blog.urls')),
    path('celery/',include('celeryapp.urls'))
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.blog_post_list, name='blog_post_list'),
    # path('create/', views.create_blog_post, name='create_blog_post'),
    # path('update/<int:id>', views.update_blog_post, name='update_blog_post'),
    # path('delete/<int:id>', views.delete_blog_post, name='delete_blog_post'),

    # -----------------------urls for class view----------------------
    # pk name  is must for update,delete

    path('', views.BlogListView.as_view(), name='blog_post_list'),
    path('view/<int:pk>', views.BlogDetailView.as_view(), name='view_blog'),
    path('update/<int:pk>', views.BlogUpdateView.as_view(), name='update_blog_post'),
    path('delete/<int:pk>', views.BlogDeleteview.as_view(), name='delete_blog_post'),
    
    path('create', views.BlogCreateView.as_view(), name='create_blog')

    # Define other URL patterns for your views
]

blog/models.py
from userApp.models import User
from django.db import models

class BlogPost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    publication_date = models.DateTimeField(auto_now_add=True)


    def __str__(self) -> str:
        return self.author.first_name

class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    
    def __str__(self) -> str:
        return self.post.title

    

templates/blogtemp/blog_post_list.html
{% extends 'base.html' %}

{% block content %}
{{request.user}}
  <h2>All Blogs</h2>
  {% for i in blog_posts%}
  {{i.author}}
    {{i.title}}
    {{i.content}}
    {{i.publication_date}}
    
    <a href="{% url 'view_blog' i.id %}">view blog</a>
    <a href="{% url 'update_blog_post' i.id %}">update blog</a>

    <a href="{% url 'delete_blog_post' i.id %}">delete blog</a>

    
  
  <!-- check permission that user can delete or not it object model level permission    -->
  <!-- {% if perms.blog.delete_blogpost %}
  <a href="{% url 'delete_blog_post' i.id %}">delete blog</a>
  {% endif %} -->
  

  
  <!-- check permission that user can delete or not it object model level permission    --> 
  <!-- {% if request.user.is_superuser %}
  <a href="{% url 'delete_blog_post' i.id %}">delete blog</a>
  {% endif %}   -->


    <br>
  {% endfor%}
  
  {% if messages %}
    {% for msg in messages %}
    {{msg}}
    {% endfor%}
    {% endif%}
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">
  </form>

{% endblock %}

templates/blogtemp/blogpost_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Are you sure want to delete ?
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" value="delete">
        <a href="{% url 'blog_post_list' %}">
            <input type="button" value="cancel">
        </a>
    </form>
</body>
</html>

templates/blogtemp/create_blog_post.html
{% extends 'base.html' %}

{% block content %}
  <h2>All Blogs</h2>
  <form method="POST">
    {% csrf_token %}
      {{form.as_p}}
     <input type="submit" value="submit">  
   </form>
{% endblock %}

templates/blogtemp/update_blog_post.html
{% extends 'base.html' %}

{% block content %}
  <h2>All Blogs</h2>

  {{blogpost.title}}
  <br>
  {{blogpost.author}}
  <br>
  {{blogpost.content}}
  <br>
  {{blogpost.publication_date}}
  
  
  <a href="{% url 'blog_post_list' %}">see all blog</a>

  <form method="POST">
    {% csrf_token %}
      {{form.as_p}}
     <input type="submit" value="submit">  
   </form>
{% endblock %}